AUGUMENTATION : True
IMAGE_SIZE: [224,224,3] # as per VGG16 model, for custume model need to change it
BATCH_SIZE: 16
INCLUDE_TOP : FALSE
EPOCHS : 1
CLASSESS: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01




